my_string = input("Введите слова для увеличения : ")
print(my_string.upper())
my_string = input("Введите слова для уменьшения : ")
print(my_string.lower())
print(my_string .replace(" ", ""))
print(my_string[0])
print(my_string[-1])